language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: true
# uncomment the following lines to override the default test script
after_success:
 - julia -e 'cd(Pkg.dir("WoodburyMatrices")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
